# Generated by Django 4.1 on 2022-09-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amenity",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="amenity",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="room",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="room",
            name="updated_at",
        ),
    ]
