# Generated by Django 4.1 on 2022-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='superuser',
        ),
        migrations.AlterField(
            model_name='house',
            name='pets_allowed',
            field=models.BooleanField(default=False, help_text='Does this house allow pets?', verbose_name='Pets Allowed?'),
        ),
    ]
